import { Provider } from './types';

export const mockProviders: Provider[] = [
  {
    id: 'p1',
    name: 'Ustad Ali',
    service: 'AC Technician',
    location: 'G-13, Islamabad',
    distance: 2.1,
    rating: 4.8,
    reviews: 124,
    baseRate: 2000,
    availability: 'now',
    phone: '0300-1234567',
    image: 'https://i.pravatar.cc/150?u=ustad ali',
  },
  {
    id: 'p2',
    name: 'Rizwan Electrics',
    service: 'Electrician',
    location: 'Bahria Town, Rawalpindi',
    distance: 3.5,
    rating: 4.6,
    reviews: 89,
    baseRate: 1500,
    availability: 'today',
    phone: '0333-7654321',
    image: 'https://i.pravatar.cc/150?u=rizwana',
  },
  {
    id: 'p3',
    name: 'Bashir Plumber',
    service: 'Plumber',
    location: 'F-8, Islamabad',
    distance: 5.2,
    rating: 4.9,
    reviews: 210,
    baseRate: 1800,
    availability: 'now',
    phone: '0311-9988776',
    image: 'https://i.pravatar.cc/150?u=bashir',
  },
  {
    id: 'p4',
    name: 'Kamran AC cooling',
    service: 'AC Technician',
    location: 'G-11, Islamabad',
    distance: 4.0,
    rating: 4.2,
    reviews: 45,
    baseRate: 1800,
    availability: 'today',
    phone: '0300-1122334',
    image: 'https://i.pravatar.cc/150?u=kamraaan',
  },
  {
    id: 'p5',
    name: 'Saeed Electrician',
    service: 'Electrician',
    location: 'Bahria Town, Rawalpindi',
    distance: 1.2,
    rating: 4.7,
    reviews: 156,
    baseRate: 1600,
    availability: 'now',
    phone: '0345-5566778',
    image: 'https://i.pravatar.cc/150?u=saeeed',
  },
  {
    id: 'p6',
    name: 'Dilawar Khan',
    service: 'Carpenter',
    location: 'Saddar, Rawalpindi',
    distance: 4.5,
    rating: 4.5,
    reviews: 67,
    baseRate: 2500,
    availability: 'now',
    phone: '0321-4455667',
    image: 'https://i.pravatar.cc/150?u=dilawar',
  },
  {
    id: 'p7',
    name: 'Smart Cleaning Co.',
    service: 'Cleaner',
    location: 'Blue Area, Islamabad',
    distance: 1.8,
    rating: 4.9,
    reviews: 312,
    baseRate: 3500,
    availability: 'today',
    phone: '0312-7788990',
    image: 'https://i.pravatar.cc/150?u=cleaning',
  },
  {
    id: 'p8',
    name: 'Irfan Painter',
    service: 'Painter',
    location: 'DHA Phase 2, Islamabad',
    distance: 6.2,
    rating: 4.3,
    reviews: 54,
    baseRate: 1200,
    availability: 'tomorrow',
    phone: '0301-2233445',
    image: 'https://i.pravatar.cc/150?u=irfan',
  },
  {
    id: 'p9',
    name: 'Aslam Masonry',
    service: 'Mason',
    location: 'Satellite Town, Rawalpindi',
    distance: 3.8,
    rating: 4.7,
    reviews: 128,
    baseRate: 2200,
    availability: 'now',
    phone: '0334-6677889',
    image: 'https://i.pravatar.cc/150?u=aslam',
  },
  {
    id: 'p10',
    name: 'Nadeem Pest Control',
    service: 'Pest Control',
    location: 'E-11, Islamabad',
    distance: 2.5,
    rating: 4.6,
    reviews: 95,
    baseRate: 4000,
    availability: 'today',
    phone: '0315-5544332',
    image: 'https://i.pravatar.cc/150?u=nadeem',
  },
  {
    id: 'p11',
    name: 'Zafar Plumber',
    service: 'Plumber',
    location: 'G-11, Islamabad',
    distance: 0.8,
    rating: 4.4,
    reviews: 42,
    baseRate: 1400,
    availability: 'now',
    phone: '0302-1112223',
    image: 'https://i.pravatar.cc/150?u=zafar',
  },
  {
    id: 'p12',
    name: 'Hassan Solar Tech',
    service: 'Solar Installer',
    location: 'Gulberg, Islamabad',
    distance: 7.5,
    rating: 4.9,
    reviews: 18,
    baseRate: 5000,
    availability: 'tomorrow',
    phone: '0316-9988771',
    image: 'https://i.pravatar.cc/150?u=hassan',
  },
  {
    id: 'p13',
    name: 'Muneeb Gardener',
    service: 'Gardener',
    location: 'F-6, Islamabad',
    distance: 3.2,
    rating: 4.7,
    reviews: 45,
    baseRate: 1500,
    availability: 'now',
    phone: '0300-4455661',
    image: 'https://i.pravatar.cc/150?u=muneeb',
  },
  {
    id: 'p14',
    name: 'Safe-Guard Security',
    service: 'Security Guard',
    location: 'DHA Phase 1, Islamabad',
    distance: 8.5,
    rating: 4.8,
    reviews: 120,
    baseRate: 4500,
    availability: 'today',
    phone: '0311-2233446',
    image: 'https://i.pravatar.cc/150?u=security',
  },
  {
    id: 'p15',
    name: 'Basharat Auto Fix',
    service: 'Auto Mechanic',
    location: 'I-9, Islamabad',
    distance: 5.0,
    rating: 4.5,
    reviews: 88,
    baseRate: 2000,
    availability: 'now',
    phone: '0344-9988775',
    image: 'https://i.pravatar.cc/150?u=basharat',
  },
  {
    id: 'p16',
    name: 'Master Home Repairs',
    service: 'Appliance Repair',
    location: 'PWD, Islamabad',
    distance: 12.0,
    rating: 4.6,
    reviews: 74,
    baseRate: 2500,
    availability: 'today',
    phone: '0300-7766554',
    image: 'https://i.pravatar.cc/150?u=repair',
  },
  {
    id: 'p17',
    name: 'Punjab Master Fixers',
    service: 'General Maintenance (AC, Electric, Plumbing, Cleaning)',
    location: 'Rawal Road, Rawalpindi',
    distance: 2.0,
    rating: 4.9,
    reviews: 540,
    baseRate: 3000,
    availability: 'now',
    phone: '0321-1112223',
    image: 'https://i.pravatar.cc/150?u=punjabmaster',
  },
  {
    id: 'p18',
    name: 'Capital Allied Services',
    service: 'All-in-One Home Solutions',
    location: 'Blue Area, Islamabad',
    distance: 1.5,
    rating: 4.8,
    reviews: 420,
    baseRate: 2800,
    availability: 'now',
    phone: '0333-5556667',
    image: 'https://i.pravatar.cc/150?u=capitalallied',
  },
  {
    id: 'p19',
    name: 'Swift Movers',
    service: 'Movers & Packers',
    location: 'G-8, Islamabad',
    distance: 4.2,
    rating: 4.4,
    reviews: 92,
    baseRate: 8000,
    availability: 'today',
    phone: '0345-1234512',
    image: 'https://i.pravatar.cc/150?u=movers',
  },
  {
    id: 'p20',
    name: 'Amina Tailoring',
    service: 'Tailor',
    location: 'Tench Bhata, Rawalpindi',
    distance: 6.8,
    rating: 4.7,
    reviews: 56,
    baseRate: 1000,
    availability: 'tomorrow',
    phone: '0301-8877665',
    image: 'https://i.pravatar.cc/150?u=amina',
  },
  {
    id: 'p21',
    name: 'Eco-Volt Solar',
    service: 'Solar Installer',
    location: 'I-8, Islamabad',
    distance: 2.3,
    rating: 4.8,
    reviews: 142,
    baseRate: 4800,
    availability: 'now',
    phone: '0344-1122338',
    image: 'https://i.pravatar.cc/150?u=ecovolt',
  },
];
